spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**
  main:
    web-application-type: reactive
server:
  port: 8084

